; Author: David Diaz, Bailey Kwok, Ryan Reeves, Brian Scott
; Class: CS140 Assembly Language and Computer Architecture.
; File Name: Grocery.inc
; Creation Date: 10/24/2023
; Program Description: Describe with a short paragraph the purpose of this file.


INCLUDE Irvine32.inc			;Use Irvine32 library.


;Provide below the prototype/s of the user-defined procedures in your program.

GroceryMenu PROTO
Dairy_op PROTO
Produce_op PROTO
Meats_op PROTO
Beverages_op PROTO
ExitProgram_op PROTO